spring:
  application:
    name: spring-cloud-registry
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # 关闭注册中心自我保护机制
    enable-self-preservation: true
    # 注册中心清理间隔（单位毫秒，默认60*1000）
    eviction-interval-timer-in-ms: 10000